Ignore markdown codeblocks for tags
dullage/flatnotes pull request #66
Opened 2023-05-08 17:11 UTC by elmodor

Hello,

I took a quick look on how to exclude tags inside markdown codeblocks.
This should help out for #35 

I'm using a second regex to remove all markdown codeblocks.
However, this will also remove the markdown from the return value of `extract_tags`.

I tested the code with various markdown codeblocks. The tag `#TagIgnore` does not show up when searching for `tags:tagignore` while `tags:tagok` shows up. 
Tested with following file:

> Testing
> 
> ``` bash
> Testing more
> #TagIgnore me please
> and this one too #TagIgnore
> ```
> 
> #TagOk
> 
> ` More to #TagIgnore `
> ` One more to
> #TagIgnore `
> `#TagIgnore`
> 
> What is going on? #TagOk
> EOF

2023-05-09 07:21 UTC, dullage commented
Thanks for giving this a go. When I get some time I'll take a look and run some tests 👍

2023-05-13 09:21 UTC, dullage commented
Hi @elmodor, I've had a look at this this morning and have some thoughts.

My first thought is that `MARKDOWN_RE` should probably be named `CODEBLOCK_RE` and `content_ex_markdown` should be `content_ex_codeblocks`. A small point but help with the diagram below.

I also think that codeblock content should still be indexed and therefore searchable. Just not as tags. So I think we need to something along these lines:

![image](https://github.com/dullage/flatnotes/assets/16575268/9d345c8f-f673-4107-8505-2f5ded13e941)

2023-05-13 09:32 UTC, elmodor commented
I agree, I should have named it `codeblock` obviously. 

Regarding your diagram, I think there should not be a line from tags to content_ex_tags?
As far as I see, we would use content_ex_codeblocks to obtain the tags but use content to obtain content_ex_tags just as before?
```
content_ex_codeblock = re.sub(cls.CODEBLOCK_RE, '', content)
_, tags = re_extract(cls.TAGS_RE, content_ex_codeblock)
content_ex_tags, _ = re_extract(cls.TAGS_RE, content)
```

2023-05-13 10:00 UTC, dullage commented
I had in mind to use `tags` to know what to remove from `content` to get `content_ex_tags`. We could, as you propose, just use the TAGS_RE again but this would mean that comments in codeblocks wouldn't get indexed at all (either as content or tags).

Of course, I can imagine the most efficient way of doing all of this would be to update `TAGS_RE` to simply ignore anything within a codeblock. Then we'd only need to run regex once (as it is now). My concern would be that the TAGS_RE would become unwieldy (even more than it is now). So splitting up the process as proposed above may be the better (more understandable) way of doing things. Even if not the most efficient.

2023-05-20 23:07 UTC, elmodor commented
I wasn't able to get one line `TAGS_RE` to work so I updated it to my last suggested code change.
If someone can wrap their head around the regex maybe they will be able to figure it out :D

2023-05-21 15:10 UTC, dullage commented
The changes look good. When I get a chance I just want to run a couple of tests on my dataset. I'm interested to see if there's much of a change to the indexing speed and I'm also keen to see the difference in tags before and after this change.

2023-05-21 15:35 UTC, dullage requested changes
Please bump `INDEX_SCHEMA_VERSION` constant to 4. This will force an index rebuild when flatnotes is updated.

2023-05-21 15:37 UTC, dullage commented
Index rebuild times seem unchanged and having compared my list of indexed tags before and after the changes, I can confirm the hashtags found in code blocks are no longer indexed. Just one change requested and then this is ok to merge.

2023-05-21 17:36 UTC, merged