Assign ID to headers with CustomHTMLRenderer
dullage/flatnotes pull request #84
Opened 2023-06-30 14:35 UTC by pbogre

I used ToastUI's [`customHTMLRenderer`](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-html-renderer.md) to assign an `id` attribute to all headers equal to the sanitized version of the text of that header.

a simplified version of this can be found in the customHTMLRenderer docs linked above, but my version is a little more extensive in the way it sanitizes the text as it removes all non-alphanumerical characters. Here are some examples of the sanitization:

- `"$$!!£!HeADinG \\1!  !" -> "heading-1"` 
- `"Slightly more 'normal' heading 2" -> "slightly-more-normal-heading-2"`
- you can test this yourself with this [jsfiddle](https://jsfiddle.net/9hr1uy2f/)

the sanitized text is then set as the header's id attribute, which allows for linking in markdown, and therefore tables of content and header tagging (#34). This is very similar, in fact practically the exact same, as how it is done in github, as shown below:

`[link to section 1](#section-1)` links to header with text that sanitizes to `"section-1"`
so for instance `# Section 1` or `### SECTION 1!`

The use of `customHTMLRenderer` is a really powerful addition, as it allows to add any parameters that you want to add in the future, like [latex support](https://nhn.github.io/tui.editor/latest/tutorial-example13-creating-plugin) (#61)

I tested this on my homeserver which runs in docker and everything ran smoothly and as expected. Perhaps some more testing could be done to see if the sanitizer works as intended for all titles, but because flatnotes is selfhosted this doesnt create any security flaw and as it stands now this solution works for everyday users as most people dont need fancy symbols in their headers.

2023-06-30 16:20 UTC, dullage commented
Hey @pbogre, this looks great! As soon as I get a chance I'll have a look and try and get it merged in. It would be a great addition.

2023-06-30 20:03 UTC, pbogre commented
was just testing this now and reinstalled the image, but i got a console error saying that `customHTMLRenderer` wasn't defined correctly. Silly me. the latest commit fixes that and has also been tested by declaring `customHTMLRenderer` inside the `data` function.

2023-07-02 12:55 UTC, dullage requested changes
I had a play around with this change today and it looks good. Just a couple of minor change requests then I can get it merged in.

2023-07-02 12:55 UTC, dullage commented on flatnotes/src/components/NoteViewerEditor.vue
> +    const customHTMLRenderer = {
I'm not sure about the position of the `const` declaration here. Can we please move it outside of the Vue object. Between the imports and the `export default {` line.

2023-07-02 12:55 UTC, dullage commented on flatnotes/src/components/NoteViewerEditor.vue
> +        customHTMLRenderer: customHTMLRenderer,
Is there a benefit in adding the customHTMLRenderer to the editor? I can't see one but maybe I missed something.

2023-07-02 12:55 UTC, dullage commented on flatnotes/src/components/NoteViewerEditor.vue
> +	      id: getChildrenText(node)
In general, I like the approach here. It does a good job of creating a sane id. 👍

There is, however, an issue with duplicate header names but I appreciate that tackling this problem would significantly increase the work required. Hopefully it won't be a problem for most and if it were fixed in the future it wouldn't be a breaking change as the duplicate headers wouldn't work anyway.

2023-07-02 13:09 UTC, pbogre commented on flatnotes/src/components/NoteViewerEditor.vue
> +        customHTMLRenderer: customHTMLRenderer,
if i dont add it in the editor then the "preview" mode won't assign id's to headers and therefore header links wont work when previewing the note while editing it

2023-07-02 13:11 UTC, dullage commented on flatnotes/src/components/NoteViewerEditor.vue
> +        customHTMLRenderer: customHTMLRenderer,
Ah, of course. I forget about that feature! 🤦‍♂️

2023-07-02 13:11 UTC, pbogre commented on flatnotes/src/components/NoteViewerEditor.vue
> +	      id: getChildrenText(node)
the way it works with duplicate headers is that it link to the first match, i believe this is default behaviour with linking to sections in general not just markdown

2023-07-02 13:15 UTC, dullage commented on flatnotes/src/components/NoteViewerEditor.vue
> +	      id: getChildrenText(node)
Sure, what I mean is that we could handle it in a way similar to [Hugo](https://gohugo.io/content-management/cross-references/#heading-ids) whereby Hugo will append a number to the duplicate ids e.g. `my-header`, `my-header-1`, `my-header-2` etc... But as I say, a lot more work for something that hopefully isn't a frequent problem.

2023-07-02 13:19 UTC, pbogre commented on flatnotes/src/components/NoteViewerEditor.vue
> +    const customHTMLRenderer = {
you're right, latest commit should address this :)

2023-07-02 13:23 UTC, dullage approved these changes

2023-07-02 13:24 UTC, merged

2023-07-02 13:28 UTC, pbogre commented on flatnotes/src/components/NoteViewerEditor.vue
> +	      id: getChildrenText(node)
ah i see what you mean know. the way i could see this being done is by creating a map of assigned id's, where the key is the id name and the value is the amount of times it was assigned, and then when creating the id first check if it exists in the map and then append the value and increment it by 1. i'll try to do something like this now but i'm not sure if it customHTMLRenderer will work properly with this